### ISSUE TITLE
Add option to take dark measurements during traverse

### ISSUE THREAD

**Issue by dnorgaard-usgs** [NOVACProject/MobileDOAS#69]
Without restarting software.  This is in case there is a big temperature change from start to where plume is.  This may be as easy as allowing user to specify which spectra to use as dark during re-evaluation.  Then user can just take periodic dark measurements by covering the scope.

Suggested by Bo.

**Comment by mattias42** [comment]
Actually, the program does update the dark-spectrum used if a new dark spectrum is encountered during the traverse. The problems with this are that 1) the program is really picky about when a spectrum is considered to be a dark which leads to the program not using these dark measurements all the time and 2) the program doesn't really inform the user about the fact that the dark spectrum has been updated.
The code for replacing the dark-spectrum resided in CSpectrometer::GetSpectrumInfo. This is a function which really should be refactored since it does too many things, much more than what the name of the function implies.

**Comment by dnorgaard-usgs** [comment]
Add back in the 'Dark' tab from ReEvaluation dialog?

**Comment by dnorgaard-usgs** [comment]
New ticket opened to add 'Dark' tab back in.  User dark spectrum can also be specified in 'Sky' tab if User sky spectrum is also specified.  See #112.
