### ISSUE TITLE
MobileDoas program doesn’t always fully close down when spectra collection is stopped

### ISSUE THREAD

**Issue by dnorgaard-usgs** [NOVACProject/MobileDOAS#80]
Reported by Alan L:

MobileDoas program doesn’t always fully close down when spectra collection is stopped. A process keeps running in the background, preventing spectrometers from being re-located when a new instance of mobileDOAS is initiated.

**Comment by dnorgaard-usgs** [comment]
I have seen something like this before during development.  Lately though I have not run into the issue, and still am unable to replicate.  It might be that another change made fixed this issue. Will need to watch and see.

**Comment by mattias42** [comment]
This is a tricky thing to find since it is most likely due to a threading problem inside the program... 

That being said, I think I have found and solved one possible reason for the program not closing down properly. Fix is included in commit 000827948e87a85b83aa8a27fc067b353d2b6bfd to https://github.com/mattias42/MobileDOAS/ where the spectrometer is no longer allowed to talk to the view when the program is closing down.

Lets test this and see if this was the one problem or if there are more causes for the program to not close properly.

**Comment by dnorgaard-usgs** [comment]
I have not noticed this recently.  Will close for now and reopen if seen again.
