### ISSUE TITLE
Very long characterization of dark spectra in adaptive mode

### ISSUE THREAD

**Issue by christophkern** [NOVACProject/MobileDOAS#87]
It currently takes a very long time to characterize the dark spectra when using adaptive mode, particularly when using a dual-channel spectrometer. I recommend we reduce this time by reducing the number of spectra collected for characterization of the offset. Currently, it appears that 6,000 spectra are recorded at 3 ms. I suggest using 1,000 spectra instead. This should be sufficient. If wanted, one could also provide an option for changing these parameters, i.e. the user could set the number of spectra for offset characterization and the exposure time for dark current characterization (currently fixed at 10 seconds I think). But just reducing the default number of spectra for offset characterization to 1,000 would be simple and save a lot of time.

**Comment by dnorgaard-usgs** [comment]
Updated code under adaptive mode to below.  Let me know if you think a different combination should be used.

	//m_sumInComputer       = 400;
	//m_sumInSpectrometer   = 15;
	m_sumInComputer = 100;     // number to integrate in computer
	m_sumInSpectrometer = 10;  // number to integrate in spectrometer

**Comment by dnorgaard-usgs** [comment]
Adjusted per...

On Thu, Jul 19, 2018 at 12:49 PM, Kern, Christoph wrote:
Hi Diana

thanks for this. Summing in the spectrometer is much faster than summing in the computer. Therefore, it's probably best to leave suminspectrometer at 15. Maybe just change sumincomputer to from 400 to 100. I know that give 1500 spectra rather than 1000, but it will still accelerate things by a factor of 4.

Thanks

Christoph
